baseurl = "http://blog.altostratus.me/"
languageCode = "en-us"
title = "Altostratus - high in the clouds site"
# Enable comments by entering your Disqus shortname
disqusShortname = "altostratus"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-131453936-1"
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"


[permalinks]
    post = "/:year/:month/:day/:slug"


[params]
    # Tell me who you are
    author = "Elena Neroslavskaya"
    bio = "Blogger - Programmer - Architect"
    location = "Azure"
    site_description = ""
    copyright  = "Powered by [Hugo](//gohugo.io)."
    avatar = "images/me.png"
    # Enter your email address to display your Gravatar icon in the profile. If not set the theme
    # will fallback to the avatar.
    # gravatar = "lenisha@gmail.com"
    logo = "css/images/logo.png"
    disable_mathjax = false # set to true to disable MathJax

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["post"]

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = ["css/altostratus.css"]
	custom_js  = []
    socialShare = true

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://twitter.com/enerosweb"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "lenisha"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = "lenisha"
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "neros"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "enerosweb"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    tag_cloud = true
    categories = true
    tags = true
  
